version: '3.8'

services:
  todo-java:
    build: 
      context: ./java
      dockerfile: Dockerfile.dev
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./java/src:/app/src
