server:
  port: 8003

spring:
  datasource:
    url: jdbc:h2:mem:interviewdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    
  h2:
    console:
      enabled: true
      path: /h2-console

aws:
  bedrock:
    region: us-east-1
    model-id: anthropic.claude-3-sonnet-20240229-v1:0

logging:
  level:
    com.example.interview: DEBUG
    software.amazon.awssdk: INFO